### ISSUE TITLE
Locks up on Ctrl-S

### ISSUE THREAD

**Issue by Thynix** [Thynix/Cavez-of-Phear#1]
The entire program locks on input given ctrl-s. Likely some ncurses issue. It doesn't seem to occur with other ctrl-letter combinations.

**Comment by oonis-zz** [comment]
When it locks, what happens when you hit ctrl-Q? Does that unlock it by any chance?

**Comment by Thynix** [comment]
Indeed it does. This is an intentional terminal-level thing?

**Comment by oonis-zz** [comment]
ctrl-s is used to freeze the screen on the terminal (stop any outputs). I believe it'll still run the program, it just won't output anything new until you press ctrl-Q.

**Comment by Thynix** [comment]
Ah, okay. Thank you!
